CREATE DATABASE IF NOT EXISTS posyandu CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE posyandu;

CREATE TABLE IF NOT EXISTS staff (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(80) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 name VARCHAR(120) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ibu_hamil (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 phone VARCHAR(30),
 address TEXT,
 birth_date DATE NULL,
 hpht DATE NULL,
 edd DATE NULL,
 pregnancy_number TINYINT UNSIGNED NULL,
 notes TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bayi_balita (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 mother_name VARCHAR(150),
 birth_date DATE NULL,
 gender VARCHAR(20),
 weight DECIMAL(5,2) NULL,
 height DECIMAL(5,2) NULL,
 head_circumference DECIMAL(5,2) NULL,
 notes TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 phone VARCHAR(30) NOT NULL,
 service VARCHAR(120),
 requested_date DATE NULL,
 message TEXT,
 status ENUM('Menunggu','Dikonfirmasi','Selesai','Dibatalkan') NOT NULL DEFAULT 'Menunggu',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
