<?php
session_start(); if(!isset($_SESSION['parent_id'])){header('Location: login.php');exit;}
require_once __DIR__.'/../config/database.php';
$child=null;$mother=null;$points=[];$anc=[];
if(!empty($_SESSION['parent_child_id'])){$s=$pdo->prepare('SELECT * FROM bayi_balita WHERE id=?');$s->execute([(int)$_SESSION['parent_child_id']]);$child=$s->fetch();if($child){$s=$pdo->prepare('SELECT service_date,weight,height,head_circumference FROM pelayanan_balita WHERE child_id=? ORDER BY service_date ASC');$s->execute([$child['id']]);$points=$s->fetchAll();}}
if(!empty($_SESSION['parent_mother_id'])){$s=$pdo->prepare('SELECT * FROM ibu_hamil WHERE id=?');$s->execute([(int)$_SESSION['parent_mother_id']]);$mother=$s->fetch();if($mother){$s=$pdo->prepare('SELECT * FROM pemeriksaan_ibu_hamil WHERE mother_id=? ORDER BY examination_date DESC LIMIT 10');$s->execute([$mother['id']]);$anc=$s->fetchAll();}}
$jadwal=$pdo->query("SELECT * FROM jadwal_posyandu WHERE event_date >= CURDATE() ORDER BY event_date,event_time LIMIT 5")->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard Kesehatan</title><link rel="stylesheet" href="../css/style.css"><link rel="stylesheet" href="../css/staff.css"></head>
<body class="staff-body"><div class="dashboard"><aside class="sidebar"><div class="brand">♡ Posyandu Bina Warga</div><nav><a class="active" href="dashboard.php">Dashboard Kesehatan</a><a href="#jadwal">Jadwal Posyandu</a><a href="#edukasi">Edukasi</a><a href="logout.php">Logout</a></nav></aside><main class="main-area">
<div class="topbar"><div><h1>Halo, <?=htmlspecialchars($_SESSION['parent_name'])?></h1><p>Ringkasan kesehatan yang tersedia dari data Posyandu.</p></div></div>
<?php if($child):?><div class="panel-box"><div class="panel-title-row"><h2><?=htmlspecialchars($child['name'])?></h2><a class="small-btn" href="../staff/print-kms.php?child_id=<?=$child['id']?>" target="_blank">🖨 Cetak KMS</a></div><p>Tanggal lahir: <?=htmlspecialchars($child['birth_date']?:'-')?> · Jenis kelamin: <?=htmlspecialchars($child['gender']?:'-')?></p>
<?php if(count($points)>0): $maxW=max(15.0,max(array_map(fn($x)=>(float)($x['weight']??0),$points))+2);$minW=max(0.0,min(array_map(fn($x)=>(float)($x['weight']??0),$points))-2);$range=max(1,$maxW-$minW);$w=760;$h=300;$pl=55;$pr=20;$pt=20;$pb=50;$iw=$w-$pl-$pr;$ih=$h-$pt-$pb;$coords=[];foreach($points as $i=>$ptx){$x=$pl+($i/max(1,count($points)-1))*$iw;$y=$pt+(1-(((float)$ptx['weight']-$minW)/$range))*$ih;$coords[]=[$x,$y];}?>
<div class="chart-wrap"><svg viewBox="0 0 <?=$w?> <?=$h?>" class="growth-chart"><line x1="<?=$pl?>" y1="<?=$pt?>" x2="<?=$pl?>" y2="<?=$h-$pb?>" stroke="currentColor" opacity=".25"/><line x1="<?=$pl?>" y1="<?=$h-$pb?>" x2="<?=$w-$pr?>" y2="<?=$h-$pb?>" stroke="currentColor" opacity=".25"/><?php for($i=0;$i<=4;$i++):$v=$minW+$range*$i/4;$y=$pt+(1-$i/4)*$ih;?><line x1="<?=$pl?>" y1="<?=$y?>" x2="<?=$w-$pr?>" y2="<?=$y?>" stroke="currentColor" opacity=".08"/><text x="5" y="<?=$y+5?>" font-size="12"><?=number_format($v,1)?> kg</text><?php endfor;?><?php if(count($coords)>1):?><polyline points="<?=implode(' ',array_map(fn($c)=>$c[0].','.$c[1],$coords))?>" fill="none" stroke="currentColor" stroke-width="3"/><?php endif;?><?php foreach($coords as $i=>$c):?><circle cx="<?=$c[0]?>" cy="<?=$c[1]?>" r="5" fill="currentColor"/><text x="<?=$c[0]?>" y="<?=$h-15?>" text-anchor="middle" font-size="10"><?=htmlspecialchars(date('d/m',strtotime($points[$i]['service_date'])))?></text><?php endforeach;?></svg></div><?php else:?><p>Belum ada riwayat pertumbuhan.</p><?php endif;?></div><?php endif;?>
<?php if($mother):?><div class="panel-box"><h2>Riwayat Pemeriksaan Kehamilan</h2><div class="table-wrap"><table class="data-table"><tr><th>Tanggal</th><th>Usia Kehamilan</th><th>LILA</th><th>Tekanan Darah</th><th>Keluhan</th></tr><?php foreach($anc as $r):?><tr><td><?=htmlspecialchars($r['examination_date'])?></td><td><?=htmlspecialchars($r['gestational_age_weeks']??'-')?> minggu</td><td><?=htmlspecialchars($r['lila']??'-')?> cm</td><td><?=htmlspecialchars($r['blood_pressure']?:'-')?></td><td><?=htmlspecialchars($r['complaints']?:'-')?></td></tr><?php endforeach;?></table></div></div><?php endif;?>
<div class="panel-box" id="jadwal"><h2>Jadwal Posyandu Berikutnya</h2><?php if($jadwal):?><div class="table-wrap"><table class="data-table"><tr><th>Kegiatan</th><th>Tanggal</th><th>Jam</th><th>Lokasi</th></tr><?php foreach($jadwal as $j):?><tr><td><?=htmlspecialchars($j['title'])?></td><td><?=htmlspecialchars($j['event_date'])?></td><td><?=htmlspecialchars($j['event_time']?substr($j['event_time'],0,5):'-')?></td><td><?=htmlspecialchars($j['location']?:'-')?></td></tr><?php endforeach;?></table></div><?php else:?><p>Belum ada jadwal berikutnya.</p><?php endif;?></div>
<div class="panel-box" id="edukasi"><h2>Edukasi Kesehatan Dasar</h2><ul><li>Ikuti jadwal Posyandu dan pemeriksaan sesuai anjuran petugas.</li><li>Simpan catatan kesehatan dan hasil pemeriksaan untuk dibawa saat kunjungan.</li><li>Untuk keluhan atau kondisi yang mengkhawatirkan, hubungi tenaga kesehatan.</li></ul></div>
</main></div></body></html>